services:
    area4.news.admin.news:
        class: Area4\Bundle\NewsBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: area4_news, label: Noticias }
        arguments: [null, Area4\Bundle\NewsBundle\Entity\News, Area4NewsBundle:NewsAdmin]
        calls:
            - [setTranslationDomain, [Area4NewsBundle]]

    area4.news.admin.category:
        class: Area4\Bundle\NewsBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: area4_news, label: Categorias }
        arguments: [null, Area4\Bundle\NewsBundle\Entity\Category, Area4NewsBundle:CategoryAdmin]

    area4.news.admin.imageSlider:
        class: Area4\Bundle\NewsBundle\Admin\ImageSliderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: area4_slider, label: Imagenes }
        arguments: [null, Area4\Bundle\NewsBundle\Entity\ImageSlider, Area4NewsBundle:ImageSliderAdmin]

    area4.news.admin.page:
        class: Area4\Bundle\NewsBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: area4_page, label: Páginas }
        arguments: [null, Area4\Bundle\NewsBundle\Entity\Page, Area4NewsBundle:PageAdmin]

    area4.news.admin.layout:
        class: Area4\Bundle\NewsBundle\Admin\LayoutAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: area4_page, label: Layout }
        arguments: [null, Area4\Bundle\NewsBundle\Entity\Layout, Area4NewsBundle:LayoutAdmin]